### PR TITLE
Add Hulafile

### PR DESCRIPTION
**Pull request by mrakes**
so we can build this for lwm...potentially

### CODE REVIEW

**Comment by christiank** [comment]
If we don't explicitly say `--disable-pcap` then this will contain pcap functionality if libpcap is found and/or built before this package.

We should `dep 'libpcap'` if we want/need the pcap features, otherwise, we should `--disable-pcap` to guarantee consistency

**Comment by christiank** [comment]
@angelagit

**Comment by christiank** [comment]
Otherwise i was able to build this for cosmos:lwm without issue

**Comment by mrakes** [comment]
going to merge this... probably won't add to builddef for a whiles yet...

**Pull request merged**
